---
apiVersion: v1
kind: Service
metadata:
  name: modelservice
spec:
  selector:
    app: app
  ports:
    -protocol: "TCP"
    port: 8502
    targetPort: 8502
    nodePort: 30004
  type: LoadBalancer

